// Common
const GET_ERRORS = "GET_ERRORS";

//Login/SignUp Types
const GET_REGINITIAL = "GET_REGINITIAL";
const SET_CURRENT_USER = "SET_CURRENT_USER";

// User Profile
const GET_PROFILE = "GET_PROFILE";
const PROFILE_LOADING = "PROFILE_LOADING";
const SET_PROFILE = "SET_PROFILE";
const GET_PROFILE_PICS = "GET_PROFILE_PICS";
const SET_PROFILE_PICS = "SET_PROFILE_PICS";


// Product
const GET_PRODUCT_STORE = "GET_PRODUCT_STORE";
const GET_STORE_CATEGORY = "GET_STORE_CATEGORY";
const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS";
const GET_STORE_PRODUCTS = "GET_STORE_PRODUCTS";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const GET_MOBILES = "GET_MOBILES";
const GET_LAPTOPS = "GET_LAPTOPS";
const GET_MENS_FASHION = "GET_MENS_FASHION";
const GET_WOMENS_FASHION = "GET_WOMENS_FASHION";
const GET_MENS_ACCESSORIES = "GET_MENS_ACCESSORIES";
const GET_WOMENS_ACCESSORIES = "GET_WOMENS_ACCESSORIES";
const PRODUCTS_LOADING = "PRODUCTS_LOADING";

// Single Product
const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCTS_LOADING";

const CURRENT_CATEGORY = "CURRENT_CATEGORY";
const CURRENT_STORE = "CURRENT_STORE";
const ADD_TO_CART = "ADD_TO_CART";
const LOAD_CART = "LOAD_CART";
const CART_DETAILS = "CART_DETAILS";
const CHECKOUT_INFO = "CHECKOUT_INFO";
const RESET_CART_DETAILS = "RESET_CART_DETAILS";
const RESET_CART = "RESET_CART";
const RESET_CHECKOUT_INFO = "RESET_CHECKOUT_INFO";

const SEARCH_ITEMS = "SEARCH_ITEMS";

const PRODUCTS = {
    GET_ALL_PRODUCTS,
    GET_MOBILES,
    GET_LAPTOPS,
    GET_MENS_FASHION,
    GET_WOMENS_FASHION,
    GET_MENS_ACCESSORIES,
    GET_WOMENS_ACCESSORIES,
    PRODUCTS_LOADING,
    GET_SINGLE_PRODUCT,
    SINGLE_PRODUCT_LOADING,
    GET_ERRORS,
    
    GET_PRODUCT_STORE,
    GET_STORE_CATEGORY,
    GET_CATEGORY_PRODUCTS,
    GET_STORE_PRODUCTS,

    CURRENT_CATEGORY,
    CURRENT_STORE,
    ADD_TO_CART,
    LOAD_CART,
    CART_DETAILS,
    CHECKOUT_INFO,
    RESET_CART_DETAILS,
    RESET_CART,
    RESET_CHECKOUT_INFO,

    SEARCH_ITEMS
}

export default PRODUCTS;